 # Table of Contents
<div class="toc" style="margin-top: 1em;"><ul class="toc-item" id="toc-level0"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Todo" data-toc-modified-id="Todo-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Todo</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Introduction" data-toc-modified-id="Introduction-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Background" data-toc-modified-id="Background-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Background</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Data" data-toc-modified-id="Data-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Data</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Variables" data-toc-modified-id="Variables-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Variables</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Description" data-toc-modified-id="Description-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Description</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Some-Notes-to-observe" data-toc-modified-id="Some-Notes-to-observe-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Some Notes to observe</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Data-Cleaning" data-toc-modified-id="Data-Cleaning-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Data Cleaning</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Extracting-Country-from-B_Location-and-R_Location" data-toc-modified-id="Extracting-Country-from-B_Location-and-R_Location-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Extracting Country from B_Location and R_Location</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Converting-Strings-to-Categories" data-toc-modified-id="Converting-Strings-to-Categories-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Converting Strings to Categories</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Data-Correlation" data-toc-modified-id="Data-Correlation-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Data Correlation</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Modeling" data-toc-modified-id="Modeling-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Modeling</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Trying-to-improve-results-by-dividing-features" data-toc-modified-id="Trying-to-improve-results-by-dividing-features-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Trying to improve results by dividing features</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Dropping-Round-4-and-Round-5-since-most-fights-are-3-round-Max." data-toc-modified-id="Dropping-Round-4-and-Round-5-since-most-fights-are-3-round-Max.-9.1.1"><span class="toc-item-num">9.1.1&nbsp;&nbsp;</span>Dropping Round 4 and Round 5 since most fights are 3 round Max.</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Dropping-5-round-fights-entirely" data-toc-modified-id="Dropping-5-round-fights-entirely-9.1.2"><span class="toc-item-num">9.1.2&nbsp;&nbsp;</span>Dropping 5 round fights entirely</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Dropping-First-Fights" data-toc-modified-id="Dropping-First-Fights-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Dropping First Fights</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Aggregate-Round-Stats" data-toc-modified-id="Aggregate-Round-Stats-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Aggregate Round Stats</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Comparing-Red-to-Blue" data-toc-modified-id="Comparing-Red-to-Blue-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>Comparing Red to Blue</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Reducing-Features" data-toc-modified-id="Reducing-Features-9.5"><span class="toc-item-num">9.5&nbsp;&nbsp;</span>Reducing Features</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Conclusion" data-toc-modified-id="Conclusion-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Conclusion</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Stretch-Goals" data-toc-modified-id="Stretch-Goals-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Stretch Goals</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Rewrite-and-re-run-scraper-to-pull-data-from-earlier-years" data-toc-modified-id="Rewrite-and-re-run-scraper-to-pull-data-from-earlier-years-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Rewrite and re-run scraper to pull data from earlier years</a></span></li></ul></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Scraper-Rewrite" data-toc-modified-id="Scraper-Rewrite-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Scraper Rewrite</a></span><ul class="toc-item"><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Fight-URL-Scraper" data-toc-modified-id="Fight-URL-Scraper-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>Fight URL Scraper</a></span></li><li><span><a href="http://localhost:8888/notebooks/ufc_fight_analysis/ufc_analysis.ipynb#Fight-Scraper" data-toc-modified-id="Fight-Scraper-12.2"><span class="toc-item-num">12.2&nbsp;&nbsp;</span>Fight Scraper</a></span></li></ul></li></ul></div>

# UFC Fight Analysis


## Todo


1. Create percentages column for each landed / attempted statistic
2. Aggregate all data so it's ongoing
  1. Sum each fighter's data to make it possible to compare fighters in a reasonable way
  2. One idea is to subtract two fighters' non-ratio stats and use them as labels
  3. You can still use ratio stats as labels
2. Rewrite models to account for the unbalanced data.
  1. Most fights are won by decision, so that should be accounted for

I'm just spitballing but I think the fighter with the most strikes landed will usually win. We can test this by turning each fight into differences. We will subtract one fighter's stats from the other, including strikes, submissions attempted, KO wins, KO losses, sub wins, etc. Then, we'll feed the data into the algorithm and assess the results. Currently, the algorithm is just looking at each fight's stats and judging the winner. That's not very realistic or useful tbh...

This will be a cool project, even if the results don't turn out the way I expected. We'll work on this in a couple stages:

1. Clean up data. Check for:
  1. Misspellings
  2. Logical errors (strikes landed > strikes attempted, etc)
  3. Incorrect data types
  4. Missing data
  5. Convert strings to categories? Not many categorical vars, so we'll leave this as a stretch goal.
2. Create df of running tallies. We'll have to put more thought into it, but searching for previous columns with that name and adding them together.
3. Only include non-debut fights? There will be no data for that fighter, which may skew results but I'm also curious about the outcome. I might include it anyway to see if there are any patterns.
4. In each fight, subtract one fighter's stats from the other

## Introduction

## Background

## Data

This data was forked from the [UFC Predictor and Notes](https://www.kaggle.com/calmdownkarm/ufc-predictor-and-notes) kaggle kernel. They scraped the data using Beautiful Soup and a Javascript API that pulled fighter data from ufc.com. The scripts pulled data from JSON objects and wrote them to a CSV. All data is from 2014 onwards and consists of fighter statistics merged with fight outcomes. They were unable to get data with the same level of detail in prior years, so all fighter records were reset to zero at the beginning of 2014 and built from there. It was an interesting project and I wanted to see if I could push it further.

In [1]:
# Imports and Helper Functions
# data Analysis
import pandas as pd
import numpy as np
import random as rng
from pprint import pprint

# Web Scraping
import json
import codecs
import csv
import datetime
from bs4 import BeautifulSoup
import requests
import cStringIO
import pprint

# Visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#SciKit Learn Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier


from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

from subprocess import check_output
print check_output(["ls", "data"]).decode("utf8")
data = pd.read_csv("data/data.csv")
# Any results you write to the current directory are saved as output.

# Noteboook Functionality
from IPython.core.interactiveshell import InteractiveShell # All statements are printed to output
InteractiveShell.ast_node_interactivity = "all"

data.csv
data.csv.zip



In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1477 entries, 0 to 1476
Columns: 895 entries, BPrev to winner
dtypes: float64(873), int64(13), object(9)
memory usage: 10.1+ MB


## Variables

There are 895 variables, so it might be worth looking through them to get a better sense of the data. Right now, I'm only aware of a handful of variables and have no idea how many missing values are in the dataset. At least listing the variable names will allow me to categorize them and possibly engineer new features.

In [ ]:
var_list = data.columns.values.tolist()
pprint(var_list[:100])
pprint(var_list[100:200])
pprint(var_list[200:300])
pprint(var_list[300:400])
pprint(var_list[400:500])
pprint(var_list[500:600])
pprint(var_list[600:700])
pprint(var_list[700:800])
pprint(var_list[800:895])

## Description
From this, we can see that we have a total of 879 Columns and one dependent variable. 
The columns themselves have 4 integer types (Streaks, Previous Wins etc), 5 object types (Names, Winner - basically strings and arrays) and 870 Float types. 
This however does not give us a complete picture of our data, so we're using a few other pandas functions to get a better glimpse. 
We also had to engineer a few features that weren't available in the JSONs as explained in the data explanation in the introduction of the project. 

In [3]:
data.describe()

BPrev      BStreak        B_Age     B_Height         B_ID  \
count  1477.000000  1477.000000  1474.000000  1476.000000  1477.000000   
mean      1.735274     0.654705    30.954545   177.451220  1964.633040   
std       1.895561     1.057269     4.020311     8.561541   666.949141   
min       0.000000     0.000000    20.000000   152.000000   129.000000   
25%       0.000000     0.000000    28.000000   172.000000  1755.000000   
50%       1.000000     0.000000    31.000000   177.000000  2156.000000   
75%       3.000000     1.000000    34.000000   182.000000  2337.000000   
max      11.000000     7.000000    46.000000   213.000000  2882.000000   

          B_Weight  B__Round1_Grappling_Reversals_Landed  \
count  1477.000000                            978.000000   
mean     73.804333                              0.036810   
std      14.980531                              0.193748   
min      52.000000                              0.000000   
25%      65.000000                              0.000000   
50%      70.000000                              0.000000   
75%      84.000000                              0.000000   
max     120.000000                              2.000000   

       B__Round1_Grappling_Standups_Landed  \
count                           978.000000   
mean                              0.896728   
std                               1.255722   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               1.000000   
max                               9.000000   

       B__Round1_Grappling_Submissions_Attempts  \
count                                978.000000   
mean                                   0.431493   
std                                    0.830527   
min                                    0.000000   
25%                                    0.000000   
50%                                    0.000000   
75%                                    1.000000   
max                                    6.000000   

       B__Round1_Grappling_Takedowns_Attempts             ...               \
count                              978.000000             ...                
mean                                 2.986708             ...                
std                                  3.987291             ...                
min                                  0.000000             ...                
25%                                  0.000000             ...                
50%                                  2.000000             ...                
75%                                  4.000000             ...                
max                                 33.000000             ...                

       R__Round5_TIP_Distance Time  R__Round5_TIP_Ground Control Time  \
count                   144.000000                         144.000000   
mean                    211.965278                          34.062500   
std                     139.412374                          68.819742   
min                       0.000000                           0.000000   
25%                     110.000000                           0.000000   
50%                     214.000000                           0.000000   
75%                     294.500000                          47.500000   
max                     647.000000                         496.000000   

       R__Round5_TIP_Ground Time  R__Round5_TIP_Guard Control Time  \
count                 144.000000                        144.000000   
mean                   66.604167                          5.527778   
std                    94.574736                         22.374419   
min                     0.000000                          0.000000   
25%                     2.000000                          0.000000   
50%                     9.500000                          0.000000   
75%                   109.000000                          0.000000   
max      

In [4]:
data.describe(include=['O'])

B_HomeTown             B_Location     B_Name        Date  \
count                    1471                   1470       1477        1477   
unique                    568                    431        719         224   
top     Rio de Janeiro Brazil  Rio de Janeiro Brazil  Tim Means  07/11/2016   
freq                       32                     38          8          32   

                   R_HomeTown             R_Location          R_Name winby  \
count                    1477                   1476            1477  1461   
unique                    495                    390             633     3   
top     Rio de Janeiro Brazil  Rio de Janeiro Brazil  Donald Cerrone   DEC   
freq                       44                     67              11   720   

       winner  
count    1477  
unique      4  
top       red  
freq      867

In [5]:
data.describe(include=[np.int])

BPrev      BStreak         B_ID     B_Weight     Event_ID  \
count  1477.000000  1477.000000  1477.000000  1477.000000  1477.000000   
mean      1.735274     0.654705  1964.633040    73.804333   733.943805   
std       1.895561     1.057269   666.949141    14.980531    50.851452   
min       0.000000     0.000000   129.000000    52.000000   646.000000   
25%       0.000000     0.000000  1755.000000    65.000000   687.000000   
50%       1.000000     0.000000  2156.000000    70.000000   738.000000   
75%       3.000000     1.000000  2337.000000    84.000000   780.000000   
max      11.000000     7.000000  2882.000000   120.000000   816.000000   

          Fight_ID   Last_round    Max_round        RPrev      RStreak  \
count  1477.000000  1477.000000  1477.000000  1477.000000  1477.000000   
mean   5583.656060     2.417062     3.208531     2.125254     0.721733   
std     611.609705     0.990158     0.605850     1.979199     1.136555   
min    4521.000000     1.000000     3.000000     0.000000     0.000000   
25%    5016.000000     1.000000     3.000000     1.000000     0.000000   
50%    5580.000000     3.000000     3.000000     2.000000     0.000000   
75%    6142.000000     3.000000     3.000000     3.000000     1.000000   
max    6627.000000     5.000000     5.000000    12.000000     9.000000   

          R_Height         R_ID     R_Weight  
count  1477.000000  1477.000000  1477.000000  
mean    177.436696  1766.935003    73.935003  
std       8.667657   697.191563    15.069751  
min     154.000000   129.000000    52.000000  
25%     172.000000  1253.000000    65.000000  
50%     177.000000  2015.000000    70.000000  
75%     185.000000  2255.000000    84.000000  
max     213.000000  2870.000000   120.000000

In [7]:
data['winby'].value_counts()

DEC       720
KO/TKO    458
SUB       283
Name: winby, dtype: int64

In [8]:
data['winner'].value_counts()

red           867
blue          584
no contest     17
draw            9
Name: winner, dtype: int64

### Some Notes to observe
1. Red Side seems to win slightly more than blue (867/1477 = 58.7%)
2. Donald Cerrone fights on Red side more than any other fighter, with 11 fights
3. Tim Means fights on Blue side more than any other fighter with 8
4. There are more fighters fighting debut fights. This statistic however could be skewed by the fact that our data set assumes debuts of every fighter in 2013
5. Most Fights are won by decision, and 2015 had the most fights. 
6. The Most common hometown and training location for fighters is Rei De Janeiro in Brazil
We also notice that 3 fighters don't have an age and 1 doesn't have a height. 

## Data Cleaning

The first step in data cleaning is to remove obvious outliers and columns that will not contribute to the model. One starting point is narrowing down the fights to just wins and losses, excluding no contests and draws. No contests are nearly impossible to predict as are draws, so it doesn't make sense to account for them. Here's a list of ideas so far:

1. Draws or no contest ['winner']
2. Blue and red ID
3. Blue and red Name
4. Blue and red Name
5. Date

The data is currently not in "tidy" format, so I may consider reshaping it. One obvious hint that this is the case is that every row has a round_4 and round_5 column, even though not all fights go to the last round. I'll see what I can do in terms of reshaping the data and look into whether it makes sense to do so. I wonder if there's a dplyr and tidyr package for Python? The R equivalents are pretty robust, so I'll probably start there. Here's an ongoing list of ideas that may be worth pursuing:

1. Rearrange data to get rid of empty Round4 and Round5 data
2. Separate city and country (Brazil vs RioDijanero Brazil and USA vs Stockton, California USA may add more predictive power)
3. Change landed and attempted data into percentages. This may help make better comparisons across fighters making debuts vs fighters with established records.
4. Add a column for submission wins, KO wins, etc

I'm debating whether to turn the database into a database of fighters instead of a database of fights. One reason is that you have the accumulated statistics on each fighter's history going into each event. If you have Jon Jones matching up against DC, it may be useful to ask, "What is it about Jon Jones' record that makes him a favorite? This may require a lot or rearranging, so it may be worth it to think this through a bit first.

If I were to go this route, I would reset each fighter's stats and only add stats that came prior to each fight. For example, if Frankie Edgar fought in 2013 against Anderson Silva and then fought again against Matt Hughes in 2014, I'd want their fighter record inputs to be different. I think this may be a more comprehensive way of looking at the data and would align more closely to real-world applications. Here's a rough sketch of what the process might look like:

1. Sort the dataframe by date
2. Add each fighter's stats cumulatively based on prior fights
  1. Figure out a way to accomplish this even though red is on one side and blue is on the other
  2. Maybe put fighters on just red or blue? Might be impossible..
  3. Maybe just account for this in the code? If B_Name == 'X' do this or if R_Name == 'X' do that
3. Add columns for kicks taken, punches taken, etc?
  1. One disadvantage is that this would mean nearly doubling the number of variables in a dataset that is already massive. This will hurt some machine learning models. Actually, this could lead to more variables than observations which would be no bueno, although it would still be possible to pare it down afterwards. Let's omit this for now and come back to it later if necessary.
4. Consider consolidating round data. Why do you need 5 rounds of data for each fighter? Consider building a granular model and an aggragated model.

In [9]:
data.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed   ...    R__Round5_TIP_Ground Time  \
0                                   0.0   ...                          NaN   
1                                   NaN   ...                          NaN   
2                                   0.0   ...                          NaN   
3                                   NaN   ...                          NaN   
4                                   0.0   ...                          NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [10]:
data.tail()

BPrev  BStreak  B_Age  B_Height                     B_HomeTown  B_ID  \
1472      0        0   26.0     172.0  Tlaltenango, Zacatecas Mexico  2355   
1473      2        1   26.0     165.0             Tampa, Florida USA  2610   
1474      3        2   36.0     187.0   Doylestown, Pennsylvania USA  1694   
1475      3        1   31.0     167.0                Irvine Scotland  2339   
1476      2        1   31.0     187.0                The Netherlands   786   

                           B_Location             B_Name  B_Weight  \
1472        San Diego, California USA      Jose Quinonez        61   
1473               Tampa, Florida USA      Geane Herrera        56   
1474       Dana Point, California USA    Patrick Cummins        93   
1475                 Glasgow Scotland  Joanne Calderwood        52   
1476  Leiden, Holland The Netherlands     Gegard Mousasi        84   

      B__Round1_Grappling_Reversals_Landed   ...    R__Round5_TIP_Ground Time  \
1472                                   NaN   ...                          NaN   
1473                                   0.0   ...                          0.0   
1474                                   0.0   ...                          NaN   
1475                                   0.0   ...                          0.0   
1476                                   0.0   ...                          NaN   

      R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
1472                               NaN                                    NaN   
1473                               0.0                                    0.0   
1474                               NaN                                    NaN   
1475                               0.0                                    0.0   
1476                               NaN                                    NaN   

      R__Round5_TIP_Misc. Ground Control Time  \
1472                                      NaN   
1473                                      0.0   
1474                                      NaN   
1475                                      0.0   
1476                                      NaN   

      R__Round5_TIP_Mount Control Time  R__Round5_TIP_Neutral Time  \
1472                               NaN                         NaN   
1473                               0.0                         0.0   
1474                               NaN                         NaN   
1475                               0.0                       301.0   
1476                               NaN                         NaN   

      R__Round5_TIP_Side Control Time  R__Round5_TIP_Standing Time   winby  \
1472                              NaN                          NaN     DEC   
1473                              0.0                          0.0     DEC   
1474                              NaN                          NaN     DEC   
1475                              0.0                        301.0  KO/TKO   
1476                              NaN                          NaN     SUB   

      winner  
1472     red  
1473     red  
1474    blue  
1475    blue  
1476     red  

[5 rows x 895 columns]

The head() and tail() functions give us a snapshot of the dataset's values. Not all rows and columns are represented, but it gives just enough to get a sense of how the data is organized. There are many NaN values and they need to be changed before passing the data onto the classifiers, but I want to be careful before making any changes. For instance, the winby column is extremely unbalanced and it may make sense to get rid of some of the outliers. For instance, there are a total of 16 draws and no-contests out of 1477. It makes no sense to include these since they are anomolies, so I will drop them.

### Extracting Country from B_Location and R_Location

I want to extract each figher's country location. Currently there are 438 unique locations in the dataset. This is too many categories to get a sense of where fighters are training. There may also be some correlation between a fighter's location and his or her record. The first thing I did was exclude any fighters with null values for their current location. Thankfully, there were only 8 such cases. Then I cleaned up some of the mispellings / duplicate entries (USA and United States were consolidated into just USA). Finally, I replaced all [City Country] values to [Country] values.

In [11]:
data['B_Location'].value_counts()[:10]

Rio de Janeiro Brazil                  38
Denver, Colorado USA                   27
Albuquerque, New Mexico USA            25
Coconut Creek, Florida USA             21
Sacramento, California USA             20
San Diego, California United States    19
Glendale, Arizona USA                  17
Montreal, Quebec Canada                16
Las Vegas, Nevada USA                  16
Coconut Creek, FL USA                  15
Name: B_Location, dtype: int64

In [12]:
data = data[data['winby'].notnull()]
loc_data = data[(data['B_Location'].notnull()) & data['R_Location'].notnull()]
data = data[data['winner'] != 'no contest']
#data = data.reset_index()

In [13]:
count = loc_data['B_Location'].str.split().apply(len).value_counts()
count.index = count.index.astype(str) + ' words:'
count.sort_index(inplace=True)
count

1 words:      7
2 words:    265
3 words:    527
4 words:    462
5 words:    172
6 words:     16
7 words:      4
Name: B_Location, dtype: int64

In [14]:
len(loc_data)
len(data)

1453

1449

In [15]:
locations = ['B_Location', 'R_Location']
countries = ['Japan','Singapore']
for location in locations:
    for country in countries:
        loc_data.loc[(loc_data[location] == country), location] = 'Unknown '+country

In [16]:
# This script cleans up mispellings and extracts country info from city country columns
locations = ['B_Location', 'R_Location']
new_cols = ['R_Country_Location', 'B_Country_Location']

c_dict = {
    'United': 'USA',
    'Brasil': 'Brazil',
    'Englad': 'England',
    'Czech': 'CzechRepublic',
    'Moldova': 'Moldova',
}

post_c_dict = {
    'Africa': 'South Africa',
    'CzechRepublic': 'Czech Republic',
    'PAN': 'Panama',
    'Zealand': 'New Zealand'
}
countries = ['']
for location in locations:
    for k,v in c_dict.items():
        loc_data.loc[loc_data[location].str.contains(k), location] = v

for new_col, location in zip(new_cols, locations):
    loc_data[new_col] = loc_data[location].str.split().str[-1]
for col in new_cols:
    for k,v in post_c_dict.items():
        loc_data.loc[loc_data[col].str.contains(k), col] = v

for location, col in zip(locations, new_cols):
    loc_data[location] = loc_data[col]
    del loc_data[col]
sorted(set(loc_data['B_Location'].values.tolist()))

['Argentina',
 'Australia',
 'Brazil',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Croatia',
 'Czech Republic',
 'Dagestan',
 'Denmark',
 'Ecuador',
 'England',
 'Finland',
 'France',
 'Germany',
 'Guam',
 'Iceland',
 'Ireland',
 'Italy',
 'Japan',
 'Korea',
 'Mexico',
 'Moldova',
 'Netherlands',
 'New Zealand',
 'Norway',
 'Panama',
 'Peru',
 'Philippines',
 'Poland',
 'Romania',
 'Russia',
 'Scotland',
 'Serbia',
 'Singapore',
 'South Africa',
 'Spain',
 'Sweden',
 'Taiwan',
 'Thailand',
 'USA',
 'Ukraine',
 'Wales']

In [18]:
loc_data['B_Location'].value_counts()

USA               908
Brazil            141
Canada             54
Japan              42
Poland             37
England            35
Russia             32
Australia          31
Netherlands        17
Sweden             16
Mexico             12
Ireland            12
Korea              11
Denmark             9
France              9
Scotland            9
Finland             7
China               6
Guam                6
Philippines         6
Peru                5
Germany             4
Singapore           4
Italy               4
South Africa        3
Argentina           3
Dagestan            3
Colombia            3
Norway              3
Czech Republic      3
Thailand            2
Moldova             2
Romania             2
Ecuador             2
Panama              1
Ukraine             1
Iceland             1
Wales               1
Croatia             1
Spain               1
Taiwan              1
Serbia              1
New Zealand         1
Chile               1
Name: B_Location, dtype: int64

In [19]:
data.fillna(value=0,inplace=True)

In [20]:
data.tail()

BPrev  BStreak  B_Age  B_Height                     B_HomeTown  B_ID  \
1472      0        0   26.0     172.0  Tlaltenango, Zacatecas Mexico  2355   
1473      2        1   26.0     165.0             Tampa, Florida USA  2610   
1474      3        2   36.0     187.0   Doylestown, Pennsylvania USA  1694   
1475      3        1   31.0     167.0                Irvine Scotland  2339   
1476      2        1   31.0     187.0                The Netherlands   786   

                           B_Location             B_Name  B_Weight  \
1472        San Diego, California USA      Jose Quinonez        61   
1473               Tampa, Florida USA      Geane Herrera        56   
1474       Dana Point, California USA    Patrick Cummins        93   
1475                 Glasgow Scotland  Joanne Calderwood        52   
1476  Leiden, Holland The Netherlands     Gegard Mousasi        84   

      B__Round1_Grappling_Reversals_Landed   ...    R__Round5_TIP_Ground Time  \
1472                                   0.0   ...                          0.0   
1473                                   0.0   ...                          0.0   
1474                                   0.0   ...                          0.0   
1475                                   0.0   ...                          0.0   
1476                                   0.0   ...                          0.0   

      R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
1472                               0.0                                    0.0   
1473                               0.0                                    0.0   
1474                               0.0                                    0.0   
1475                               0.0                                    0.0   
1476                               0.0                                    0.0   

      R__Round5_TIP_Misc. Ground Control Time  \
1472                                      0.0   
1473                                      0.0   
1474                                      0.0   
1475                                      0.0   
1476                                      0.0   

      R__Round5_TIP_Mount Control Time  R__Round5_TIP_Neutral Time  \
1472                               0.0                         0.0   
1473                               0.0                         0.0   
1474                               0.0                         0.0   
1475                               0.0                       301.0   
1476                               0.0                         0.0   

      R__Round5_TIP_Side Control Time  R__Round5_TIP_Standing Time   winby  \
1472                              0.0                          0.0     DEC   
1473                              0.0                          0.0     DEC   
1474                              0.0                          0.0     DEC   
1475                              0.0                        301.0  KO/TKO   
1476                              0.0                          0.0     SUB   

      winner  
1472     red  
1473     red  
1474    blue  
1475    blue  
1476     red  

[5 rows x 895 columns]

In [21]:
dropdata = data.drop(['B_ID','B_Name','R_ID','R_Name','Date'],axis=1)
dropdata.rename(columns={'BPrev':'B__Prev',
                         'RPrev':'R__Prev',
                         'B_Age':'B__Age',
                         'B_Height':'B__Height',
                         'B_Weight':'B__Weight',
                         'R_Age':'R__Age',
                         'R_Height':'R__Height',
                         'R_Weight':'R__Weight',
                         'BStreak':'B__Streak',
                         'RStreak': 'R__Streak'},inplace=True)
dropdata.describe()

B__Prev    B__Streak       B__Age    B__Height    B__Weight  \
count  1449.000000  1449.000000  1449.000000  1449.000000  1449.000000   
mean      1.743271     0.656315    30.882678   177.328502    73.753623   
std       1.894033     1.057349     4.239225     9.760730    14.921874   
min       0.000000     0.000000     0.000000     0.000000    52.000000   
25%       0.000000     0.000000    28.000000   172.000000    65.000000   
50%       1.000000     0.000000    31.000000   177.000000    70.000000   
75%       3.000000     1.000000    34.000000   182.000000    84.000000   
max      11.000000     7.000000    46.000000   213.000000   120.000000   

       B__Round1_Grappling_Reversals_Landed  \
count                           1449.000000   
mean                               0.024155   
std                                0.158015   
min                                0.000000   
25%                                0.000000   
50%                                0.000000   
75%                                0.000000   
max                                2.000000   

       B__Round1_Grappling_Standups_Landed  \
count                          1449.000000   
mean                              0.596273   
std                               1.101487   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               1.000000   
max                               9.000000   

       B__Round1_Grappling_Submissions_Attempts  \
count                               1449.000000   
mean                                   0.287095   
std                                    0.709334   
min                                    0.000000   
25%                                    0.000000   
50%                                    0.000000   
75%                                    0.000000   
max                                    6.000000   

       B__Round1_Grappling_Takedowns_Attempts  \
count                             1449.000000   
mean                                 1.990338   
std                                  3.558690   
min                                  0.000000   
25%                                  0.000000   
50%                                  0.000000   
75%                                  3.000000   
max                                 33.000000   

       B__Round1_Grappling_Takedowns_Landed             ...               \
count                           1449.000000             ...                
mean                               0.807453             ...                
std                                1.545641             ...                
min                                0.000000             ...                
25%                                0.000000             ...                
50%                                0.000000             ...                
75%                                1.000000             ...                
max                               17.000000             ...                

       R__Round5_TIP_Distance Time  R__Round5_TIP_Ground Control Time  \
count                  1449.000000                        1449.000000   
mean                     21.064872                           3.385093   
std                      77.094035                          23.909115   
min                       0.000000                           0.000000   
25%                       0.000000                           0.000000   
50%                       0.000000                           0.000000   
75%                       0.000000                           0.000000   
max                     647.000000                         496.000000   

       R__Round5_TIP_Ground Time  R__Round5_TIP_Guard Control Time  \
count                1449.000000                       1449.000000   
mean                    6.619048                          0.549344   
std                    35.786002                  

In [22]:
dropdata.describe(include=['O'])

B_HomeTown             B_Location             R_HomeTown  \
count                    1449                   1449                   1449   
unique                    568                    431                    489   
top     Rio de Janeiro Brazil  Rio de Janeiro Brazil  Rio de Janeiro Brazil   
freq                       32                     38                     42   

                   R_Location winby winner  
count                    1449  1449   1449  
unique                    388     3      2  
top     Rio de Janeiro Brazil   DEC    red  
freq                       66   717    865

In [23]:
dropdata.describe(include=[np.int])

B__Prev    B__Streak    B__Weight     Event_ID     Fight_ID  \
count  1449.000000  1449.000000  1449.000000  1449.000000  1449.000000   
mean      1.743271     0.656315    73.753623   733.897861  5583.006211   
std       1.894033     1.057349    14.921874    50.767064   610.506493   
min       0.000000     0.000000    52.000000   646.000000  4521.000000   
25%       0.000000     0.000000    65.000000   687.000000  5016.000000   
50%       1.000000     0.000000    70.000000   738.000000  5579.000000   
75%       3.000000     1.000000    84.000000   780.000000  6139.000000   
max      11.000000     7.000000   120.000000   816.000000  6627.000000   

       Last_round    Max_round      R__Prev    R__Streak    R__Height  \
count   1449.0000  1449.000000  1449.000000  1449.000000  1449.000000   
mean       2.4196     3.209800     2.131125     0.722567   177.431332   
std        0.9871     0.607402     1.982152     1.140803     8.681417   
min        1.0000     3.000000     0.000000     0.000000   154.000000   
25%        1.0000     3.000000     1.000000     0.000000   172.000000   
50%        3.0000     3.000000     2.000000     0.000000   177.000000   
75%        3.0000     3.000000     3.000000     1.000000   185.000000   
max        5.0000     5.000000    12.000000     9.000000   213.000000   

         R__Weight  
count  1449.000000  
mean     73.908903  
std      15.038210  
min      52.000000  
25%      65.000000  
50%      70.000000  
75%      84.000000  
max     120.000000

### Converting Strings to Categories

Next we need to convert our object types of columns into categorical columns. This is done to sort by logical order

In [24]:
objecttypes = list(dropdata.select_dtypes(include=['O']).columns)
for col in objecttypes:
    dropdata[col] = dropdata[col].astype('category')

In [25]:
cat_columns = dropdata.select_dtypes(['category']).columns
dropdata[cat_columns] = dropdata[cat_columns].apply(lambda x: x.cat.codes)
dropdata.info()
dropdata.tail()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1449 entries, 0 to 1476
Columns: 890 entries, B__Prev to winner
dtypes: float64(873), int16(4), int64(11), int8(2)
memory usage: 9.8 MB


B__Prev  B__Streak  B__Age  B__Height  B_HomeTown  B_Location  \
1472        0          0    26.0      172.0         505         331   
1473        2          1    26.0      165.0         491         378   
1474        3          2    36.0      187.0         125         110   
1475        3          1    31.0      167.0         210         154   
1476        2          1    31.0      187.0         501         209   

      B__Weight  B__Round1_Grappling_Reversals_Landed  \
1472         61                                   0.0   
1473         56                                   0.0   
1474         93                                   0.0   
1475         52                                   0.0   
1476         84                                   0.0   

      B__Round1_Grappling_Standups_Landed  \
1472                                  0.0   
1473                                  1.0   
1474                                  0.0   
1475                                  0.0   
1476                                  0.0   

      B__Round1_Grappling_Submissions_Attempts   ...    \
1472                                       0.0   ...     
1473                                       0.0   ...     
1474                                       1.0   ...     
1475                                       0.0   ...     
1476                                       2.0   ...     

      R__Round5_TIP_Ground Time  R__Round5_TIP_Guard Control Time  \
1472                        0.0                               0.0   
1473                        0.0                               0.0   
1474                        0.0                               0.0   
1475                        0.0                               0.0   
1476                        0.0                               0.0   

      R__Round5_TIP_Half Guard Control Time  \
1472                                    0.0   
1473                                    0.0   
1474                                    0.0   
1475                                    0.0   
1476                                    0.0   

      R__Round5_TIP_Misc. Ground Control Time  \
1472                                      0.0   
1473                                      0.0   
1474                                      0.0   
1475                                      0.0   
1476                                      0.0   

      R__Round5_TIP_Mount Control Time  R__Round5_TIP_Neutral Time  \
1472                               0.0                         0.0   
1473                               0.0                         0.0   
1474                               0.0                         0.0   
1475                               0.0                       301.0   
1476                               0.0                         0.0   

      R__Round5_TIP_Side Control Time  R__Round5_TIP_Standing Time  winby  \
1472                              0.0                          0.0      0   
1473                              0.0                          0.0      0   
1474                              0.0                          0.0      0   
1475                              0.0                        301.0      1   
1476                              0.0                          0.0      2   

      winner  
1472       1  
1473       1  
1474       0  
1475       0  
1476       1  

[5 rows x 890 columns]

## Data Correlation
While it would otherwise be normal practise to draw a heatmap or correlation matrix of our data to look for linear relationships, this is highly illogical due to the sheer number of features we're currently looking at.  Instead we examine the n largest correlations with our dependent variable (winner) to look for linear relationships - as you can see from the plot below, the relationships (if they exist) are highly non-linear. This suggests that alterations to our Data Set are required. 

Further, it seems that Round 4 statistics for the Red Fighter are the more correlating, this suggests that a split or delta sort of data set should produce better results. 

In [ ]:
# Basic Correlation Matrix
# corrmat = data.corr()
# f, ax = plt.subplots(figsize=(12, 9))
# sns.heatmap(corrmat, vmax=.8, square=True);

In [ ]:
# Subset Correlation Matrix
k = 10 #number of variables for heatmap
corrmat = dropdata.corr()
cols = corrmat.nlargest(k, 'winner')['winner'].index
cm = np.corrcoef(dropdata[cols].values.T)
sns.set(font_scale=1.25)
hm = sns.heatmap(cm, cbar=True, annot=True, square=True, fmt='.2f', annot_kws={'size': 10}, yticklabels=cols.values, xticklabels=cols.values)
plt.show()

## Modeling
We're evaluating the following models

1. Perceptron
2. Random Forests
3. Decision Trees Classifier
4. SGD Classifier
5. Linear SVC
6. Gaussian NB
7. KNN

I each model's random_state when appropriate and set the SVM's class_weight to balanced to account for the unbalanced data. There's a lot that can be done in terms of tuning the hyperparameters. I may have to come back to this later to further test different configurations.

In [ ]:
# help(sklearn.ensemble.RandomForestClassifier())
# help(sklearn.naive_bayes.GaussianNB)
help(sklearn.svm.LinearSVC)
# import sklearn
# help(sklearn)

In [ ]:
# We Store prediction of each model in our dict
# Helper Functions for our models. 

def percep(X_train,Y_train,X_test,Y_test,Models):
    perceptron = Perceptron(max_iter = 1000, tol = 0.001, random_state=42)
    perceptron.fit(X_train, Y_train)
    Y_pred = perceptron.predict(X_test)
    Models['Perceptron'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]
    return

def ranfor(X_train,Y_train,X_test,Y_test,Models):
    randomfor = RandomForestClassifier(max_features="sqrt",
                                       n_estimators = 700,
                                       max_depth = None,
                                       n_jobs=-1,
                                       random_state=42
                                      )
    randomfor.fit(X_train,Y_train)
    Y_pred = randomfor.predict(X_test)
    Models['Random Forests'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]
    return

def dec_tree(X_train,Y_train,X_test,Y_test,Models):
    decision_tree = DecisionTreeClassifier(class_weight="balanced",random_state=42)
    decision_tree.fit(X_train, Y_train)
    Y_pred = decision_tree.predict(X_test)
    Models['Decision Tree'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]
    return

def SGDClass(X_train,Y_train,X_test,Y_test,Models):
    sgd = SGDClassifier(max_iter = 1000, tol = 0.001, class_weight = "balanced", random_state=42)
    sgd.fit(X_train, Y_train)
    Y_pred = sgd.predict(X_test)
    Models['SGD Classifier'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]
    return

def linSVC(X_train,Y_train,X_test,Y_test,Models):
    linear_svc = LinearSVC(class_weight="balanced", random_state=42)
    linear_svc.fit(X_train, Y_train)
    Y_pred = linear_svc.predict(X_test)
    Models['SVM'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]
    return

def bayes(X_train,Y_train,X_test,Y_test,Models):
    gaussian = GaussianNB()
    gaussian.fit(X_train, Y_train)
    Y_pred = gaussian.predict(X_test)
    Models['Bayes'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]
    return

def Nearest(X_train,Y_train,X_test,Y_test,Models):
    knn = KNeighborsClassifier(n_neighbors = 3)
    knn.fit(X_train, Y_train)
    Y_pred = knn.predict(X_test)
    Models['KNN'] = [accuracy_score(Y_test,Y_pred),confusion_matrix(Y_test,Y_pred)]

def run_all_and_Plot(df):
    Models = dict()
    from sklearn.model_selection import train_test_split
    X_all = df.drop(['winner'], axis=1)
    y_all = df['winner']
    X_train, X_test, Y_train, Y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=0)
    percep(X_train,Y_train,X_test,Y_test,Models)
    ranfor(X_train,Y_train,X_test,Y_test,Models)
    dec_tree(X_train,Y_train,X_test,Y_test,Models)
    SGDClass(X_train,Y_train,X_test,Y_test,Models)
    linSVC(X_train,Y_train,X_test,Y_test,Models)
    bayes(X_train,Y_train,X_test,Y_test,Models)
    Nearest(X_train,Y_train,X_test,Y_test,Models)
    return Models


def plot_bar(dict):
    labels = tuple(dict.keys())
    y_pos = np.arange(len(labels))
    values = [dict[n][0] for n in dict]
    plt.bar(y_pos, values, align='center', alpha=0.5)
    plt.xticks(y_pos, labels,rotation='vertical')
    plt.ylabel('accuracy')
    plt.title('Accuracy of different models')
    plt.show()


def plot_cm(dict):
    count = 1
    fig = plt.figure(figsize=(10,10))
    for model in dict:
        cm = dict[model][1]
        labels = ['W','L']
        ax = fig.add_subplot(4,4,count)
        cax = ax.matshow(cm)
        plt.title(model,y=-0.8)
        fig.colorbar(cax)
        ax.set_xticklabels([''] + labels)
        ax.set_yticklabels([''] + labels)
        plt.xlabel('Predicted')
        plt.ylabel('True')
        # plt.subplot(2,2,count)
        count+=1
    plt.tight_layout()
    plt.show()

In [ ]:
accuracies = run_all_and_Plot(dropdata)
CompareAll = dict()
CompareAll['Baseline'] = accuracies
for key,val in accuracies.items():
    print(str(key) +' '+ str(val[0]))
plot_bar(accuracies)
plot_cm(accuracies)

Theoretically, we should get best results from our Random Forests Model, thus attempting to tune hyper parameters using GridSearch from Scikit learn

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
#X_all = dropdata.drop(['winner'], axis=1)
#y_all = dropdata['winner']
#X_train, X_test, Y_train, Y_test = train_test_split(X_all, y_all, test_size=0.2, random_state=23)
#rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=50, oob_score = True, max_depth=None) 
#param_grid = { 
#    'n_estimators': [200,700],
#    'max_features': ['auto', 'sqrt', 'log2']
#}

#CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
#CV_rfc.fit(X_train, Y_train)
#print(CV_rfc.best_params_)

### Trying to improve results by dividing features

This block turns each individual red and blue round stat into a ratio of red to blue values. It divides the number of features from 895 to 450. For instance, it turns R_Round4_Strikes_Kicks_Landed and B_Round4_Strikes_Kicks_Landed into a single ratio of red to blue strikes kicks landed. Interesting approach, it appears to be part of th iteration process to see what will be most effective in this analysis.

In [ ]:
dontchange = ['winner','Event_ID','Fight_ID','Max_round','Last_round','B_Age','R_Age']
numeric_cols = [col for col in dropdata if col not in dontchange]
dropdata[numeric_cols] += 1 

In [ ]:
newDF = dropdata.copy()
blue_cols = [col for col in dropdata.columns if 'B__' in col]
red_cols = [col for col in dropdata.columns if 'R__' in col]
for (blue,red) in zip(blue_cols,red_cols):
    newkey = ''.join(str(blue).split('_')[2:])
    dropdata[newkey] = dropdata[str(blue)]/dropdata[str(red)]
    del dropdata[str(blue)]
    del dropdata[str(red)]
newDF.head()

In [ ]:
accuracies = run_all_and_Plot(dropdata)
for key,val in accuracies.items():
    print(str(key) +' '+ str(val[0]))
CompareAll['Blue/Red'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)


#### Dropping Round 4 and Round 5 since most fights are 3 round Max.

This block drops round 4 and round 5 columns from the dataset but keeps fights that last 5 rounds. It may be an attempt to overcome the amount of null values in the dataset. I'd go a different route since this doesn't seem very precise. I'd tidy and consolidate the data from all rounds into one so there wouldn't be a need to drop round 4 and 5 data. 

In [ ]:
r4 = [col for col in dropdata.columns if "Round4" in col]
r5 = [col for col in dropdata.columns if "Round5" in col]
threerounds = dropdata.drop(r4+r5,axis = 1)
accuracies = run_all_and_Plot(threerounds)
for key,val in accuracies.items():
    print(str(key)+' '+str(val[0]))
CompareAll['DropR4&R5'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)

#### Dropping 5 round fights entirely

This block drops all title fights. I think this is a mistake for a couple reasons. The dataset is small enough already (only 1477 observations) so dropping any records would probably have a negative impact on the machine learning algorithm. Also, there may be a better way to represent the data that would negate the reasoning behind this step.

In [ ]:
foobar = threerounds.loc[threerounds['Max_round'] == 3]
bewb = threerounds.drop(['Max_round','Last_round'],axis=1)
accuracies = run_all_and_Plot(bewb)
for key,val in accuracies.items():
    print(str(key)+' '+str(val[0]))
CompareAll['Drop5RoundFights'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)

### Dropping First Fights

This drops any fights in which the fighter has no previous recorded. I may use this in my model but again I'm hesitant to do so because it involves a huge loss of data. Looking at the original CSV, there are 342 records in for Red and 499 records for blue in which they have no previously recorded fight data. I can't afford to lose more than half the data.

This is actually a pretty interesting problem because I'm not sure how to deal with new fighters. By definition, their stats will show up as zeros if they don't have any fight data. It might be worth exploring how to get records prior to 2014 and going from there. Possible sources include:

1. Fightmetrics
2. Fight data from other fight organizations
3. Looking into what the original analyst meant when he said the previous data was not as granular

In [ ]:
data[data.RPrev == False]

In [ ]:
data[data.BPrev == False]

In [ ]:
blahblah = bewb[bewb.Prev != 1]
accuracies = run_all_and_Plot(blahblah)
for key,val in accuracies.items():
    print(str(key)+' '+str(val[0]))
CompareAll['DroppingDebut'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)

In [ ]:
blue_cols

### Aggregate Round Stats

This block sums the stats for each round into one value. For example, it combines round 1-5 strikes_landed into a single value. This is what I was thinking of doing. May have to borrow this code in my analysis.

In [ ]:
blue_cols
newDF.info()
b_feats = list(set([x[10:] for x in blue_cols if "Round" in x]))
r_feats = list(set([x[10:] for x in red_cols if "Round" in x]))
def sumshit(b_feats,cols):
    for x in b_feats:
        newDF.loc[:,x] = 0
        for y in cols:
            if x in y:
                newDF[x] += newDF[y]
                newDF.drop(y,axis=1,inplace=True)
sumshit(b_feats,blue_cols)
sumshit(r_feats,red_cols)
newDF.info()


In [ ]:
newDF.describe()
accuracies = run_all_and_Plot(newDF)
for key,val in accuracies.items():
    print(str(key) +' '+ str(val[0]))
CompareAll['SumRounds'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)



### Comparing Red to Blue

This block compares red stats to blue stats. It creates a ratio of strikes landed by red vs strikes landed by blue for each category. Very useful. I think I'm going to borrow this code as well since it's an idea I was thinking about implementing in my reanalysis.

In [ ]:
blue_cols = [col for col in newDF.columns if 'B__' in col]
red_cols = [col for col in newDF.columns if 'R__' in col]
for (blue,red) in zip(blue_cols,red_cols):
    newkey = ''.join(str(blue).split('_')[2:])
    newDF[newkey] = newDF[str(blue)]/newDF[str(red)]
    del newDF[str(blue)]
    del newDF[str(red)]

In [ ]:
accuracies = run_all_and_Plot(newDF)
for key,val in accuracies.items():
    print(str(key) +' '+ str(val[0]))
CompareAll['SumRounds'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)

### Reducing Features

This block drops features that are seemingly arbitrary and may have little effect on the data. It drops weight, hometown, event location, event id, fight id, max round and last round. Interestingly, the accuracy scores dip slightly after this is done. I'm not sure I agree with the decisions made here. For instance, I still want to take a look at splitting the columns by city and country. I'm not sure about the others. I'll have to combe back to this later down the road.

In [ ]:
reduced_features = newDF.drop(["Weight","B_HomeTown","B_Location", "Event_ID", "Fight_ID", "Max_round", "Last_round", "R_HomeTown", "R_Location"],axis = 1)
accuracies = run_all_and_Plot(reduced_features)
for key,val in accuracies.items():
    print(str(key) +' '+ str(val[0]))
CompareAll['Reduced Features'] = accuracies
plot_bar(accuracies)
plot_cm(accuracies)


In [ ]:
reduced_features.info()

In [ ]:
sorted(reduced_features.columns.values.tolist())

## Conclusion
Our model has a best predictive value that lies between 58-63% on average between runs. Despite a very low accuracy model, we believe this is the best possible given the amount of available data and its inherent noise. 

## Stretch Goals

### Rewrite and re-run scraper to pull data from earlier years

It won't be as granular, but it may strengthen the analysis. There might not be enough records from 2014 onwards to model the data accurately. On the other hand, I'm not even sure the previous analyst modeled the data accurately. He took fight data from each fight and used that to predict the winner. That's not realistic. You don't have a round-by-round analysis before the fight happens! It would be much better to use the running totals to predict a fight's outcome. Looks like we're learning Beautiful Soup! At least you have a starting point.


## Scraper Rewrite

The following scraper retrieves data from ufc.com. It currently pulls a single fighter's data. I added functionality to convert that data into a JSON file, extract the list of fights, and write that to a CSV but it's still incomplete. Still need the following steps:

1. Pull from list of all fighters
2. Merge all fight data so opponent data shows up
3. Flatten data where appropriate
4. Format data appropriately

I'm scrapping this and building my own scraper. The data on fightmetric is more robust. The data I'm getting from ufc.com has a lot of missing data in general and it does not break down each fight as well. It lists strike percentages but does not give raw numbers. The fightmetric data lists raw data as well as percentages and may lead to a more complete picture of each fighter. It also does not require as much merging. Looks like we're starting fresh!

### Fight URL Scraper

This first script pulls the urls of all fights from fightmetric.com and exports them as a CSV.

In [ ]:
from bs4 import BeautifulSoup
import pandas as pd
import urllib
import os
os.chdir('/Users/courtneyfergusonlee/kaggle-practice/ufc-scraper/MMA-scraper-master')

# Open the main page with events listed
sock = urllib.urlopen('http://www.fightmetric.com/statistics/events/completed?page=all')
page = sock.read()
soup = BeautifulSoup(page)

# Scrape event URLs from the main page
event_urls = []
trs = soup.find_all('tr')
for tr in trs:
    for link in tr.find_all('a'):
        event_urls.append(link.get('href'))


# Pull Fight URLs from each Event URL
fight_urls = []
for event_url in event_urls: 
    print event_url
    try:
        sock = urllib.urlopen(event_url)
        event_html = sock.read()
        event_soup = BeautifulSoup(event_html)

        tds = event_soup.find_all('td')
        for td in tds:
            for link in td.find_all('a'):
                url = link.get('href')
                url_type = url.split('-')[0][-2:] # Fight vs. Fighter; last 2 letters
                if url_type == 'ht': # use er for fighter, ht for fight
                    #print url
                    fight_urls.append(url)
    
    except urllib2.HTTPError:
        print "HTTP Error"
        pass

# Save fight URLs to a csv file
fight_urls = pd.DataFrame(fight_urls, columns=['link'])
fight_urls.to_csv('fight urls.csv', index=False)



### Fight Scraper

This scrapes all fight data from fightmetric.com/fight-details. It reads a list of URLs, pulls the fight statistics from each fight, and concatenates it onto a Pandas dataframe. There are over 4000 urls in the list, so it takes a while to run (over 3 hours).

In [28]:
from bs4 import BeautifulSoup
import pandas as pd
import urllib
import os
os.chdir('/Users/courtneyfergusonlee/ufc_fight_analysis/MMA-scraper-master')

# Load URLs from CSV (created in fightmetric_scraper.py)
fight_urls = pd.read_csv('fight urls.csv', encoding='utf-8')['link'].values.tolist()

# Initialize an empty dataframe
fighter_df = pd.DataFrame(columns=['name_first', 'name_last', 'kd', 'sig_strikes', 'sig_attempts', 'strikes', 'strike_attempts', 
                                   'takedowns', 'td_attempts', 'sub_attempts', 'pass', 'reversals', 'head', 'head_attempts', 'body', 
                                   'body_attempts','leg', 'leg_attempts', 'distance', 'distance_attempts', 'clinch', 'fight_id',
                                   'clinch_attempts', 'ground', 'ground_attempts', 'win/loss', 'referee', 'round', 'method'])


# Iterate through the fight urls, and pull relevant variables/fields
for i in range(len(fight_urls)):
    if i==10:
        print i, fight_urls[i]
        break
    
    sock = urllib.urlopen(fight_urls[i]) # specific URL for a fight
    fight_html = sock.read()
    fight_soup = BeautifulSoup(fight_html, "html.parser")
    trs = fight_soup.find_all('tr') # all the tables in each fight URL
    headers = fight_soup.find_all('i')
    bad_call = 0
    try: 
        referee = str(headers[24].get_text()).split()[1] + ' ' + str(headers[24].get_text()).split()[-1]
    except:
        referee = None
    try:
        rounds = str(headers[18].get_text()).split()[1]
    except:
        rounds = None
    try:
        method = str(headers[17].get_text()).split()[0]
    except:
        method = None
    try:
        tr1 = str(trs[1].get_text()).split()
        # Find the location of the 2nd table tr2 (it varies)
        j = 0
        while j < 10:
            if str(trs[j].get_text()).split()[6] == 'Head':
                #print j+1
                tr2 = str(trs[j+1].get_text()).split()
                j = 10
            else:
                j += 1
        #print tr1; #print tr2
        
        # Test for the end of names
        k = 0
        while k < len(tr1):
            try:
                int(tr1[k])
                break
            except:
                k += 1
                continue
        #print k
    except:
        print str(i) + ' bad call' if i%20 == 0 else None
        bad_call += 1
        continue


    # Add each fighter's information to the dataframe
    fighter1 = pd.DataFrame({'name_first': tr1[:1], 'name_last': tr1[1:2], 'kd': tr1[k], 'sig_strikes': tr1[k+2],
    'sig_attempts': tr1[k+4], 'strikes': tr1[k+10], 'strike_attempts': tr1[k+12], 'takedowns': tr1[k+16],'td_attempts': tr1[k+18],
    'sub_attempts': tr1[k+24], 'pass': tr1[k+26], 'reversals': tr1[k+28], 'head': tr2[k+8], 'head_attempts': tr2[k+10],
    'body': tr2[k+14], 'body_attempts': tr2[k+16], 'leg': tr2[k+20], 'leg_attempts': tr2[k+22], 'distance': tr2[k+26],
    'distance_attempts': tr2[k+28], 'clinch': tr2[k+32], 'clinch_attempts': tr2[k+34], 'ground': tr2[k+38], 
    'ground_attempts': tr2[k+40], 'win/loss': 1, 'referee': referee, 'round': rounds, 'method': method, 'fight_id': i})

    fighter2 = pd.DataFrame({'name_first': tr1[2:3], 'name_last': tr1[3:4], 'kd': tr1[k+1], 'sig_strikes': tr1[k+5], 
    'sig_attempts': tr1[k+7], 'strikes': tr1[k+13], 'strike_attempts': tr1[k+15], 'takedowns': tr1[k+19],'td_attempts': tr1[k+21],
    'sub_attempts': tr1[k+25], 'pass': tr1[k+27], 'reversals': tr1[k+29], 'head': tr2[k+11], 'head_attempts': tr2[k+13],
    'body': tr2[k+17], 'body_attempts': tr2[k+19], 'leg': tr2[k+23], 'leg_attempts': tr2[k+25], 'distance': tr2[k+29],
    'distance_attempts': tr2[k+31], 'clinch': tr2[k+35], 'clinch_attempts': tr2[k+37], 'ground': tr2[k+41], 
    'ground_attempts': tr2[k+43], 'win/loss': 0, 'referee': referee, 'round': rounds, 'method': method, 'fight_id': i})
    
    fighter_df = pd.concat([fighter_df, fighter1, fighter2], axis=0, ignore_index=True)
    


0

0

0

2

1

0

0

0

0

1

10 http://www.fightmetric.com/fight-details/24438a644b975751


In [29]:
# Creates a copy of the dataframe for testing
fight_df_copy = fighter_df.copy()

# Rearranges the columns so the first name, last name and win/loss appear first
cols = fight_df_copy.columns.tolist()
cols = cols[6:7] + cols[15:17] + cols[28:29] + cols[:6] + cols[7:15] + cols[17:28]
fight_df_copy = fight_df_copy[cols]
cols

# Sets the index as the fight_id
fight_df_copy.set_index('fight_id', inplace=True)

fight_df_copy
fight_df_copy.to_csv('fights.csv', index=False)

['fight_id',
 'name_first',
 'name_last',
 'win/loss',
 'body',
 'body_attempts',
 'clinch',
 'clinch_attempts',
 'distance',
 'distance_attempts',
 'ground',
 'ground_attempts',
 'head',
 'head_attempts',
 'kd',
 'leg',
 'leg_attempts',
 'method',
 'pass',
 'referee',
 'reversals',
 'round',
 'sig_attempts',
 'sig_strikes',
 'strike_attempts',
 'strikes',
 'sub_attempts',
 'takedowns',
 'td_attempts']

name_first name_last win/loss body body_attempts clinch  \
fight_id                                                           
0            Ovince     Saint        1    0             0      0   
0             Preux    Yushin        0    0             0      0   
1           Claudia   Gadelha        1    1             4      9   
1           Jessica   Andrade        0   50            58     18   
2          Takanori      Gomi        1    1             1      0   
2              Dong      Hyun        0    2             2      0   
3            Gokhan      Saki        1    2             3      1   
3          Henrique        da        0    4             5      8   
4            Teruto  Ishihara        1    6             8      2   
4           Rolando        Dy        0   15            21     13   
5           Jussier   Formiga        1    1             1      0   
5              Ulka    Sasaki        0    9            13      2   
6             Keita  Nakamura        1   14            22      0   
6              Alex    Morono        0    3             6      1   
7             Syuri     Kondo        1   26            29     12   
7            Chanmi      Jeon        0   12            27      3   
8           Shinsho     Anzai        1   13            20     28   
8              Luke    Jumeau        0    7            12     30   
9            Daichi       Abe        1    4             7      3   
9              Hyun       Gyu        0    4             6      0   

         clinch_attempts distance distance_attempts ground     ...      \
fight_id                                                       ...       
0                      0        0                 0      0     ...       
0                      0        0                 0      0     ...       
1                     15       30                71      3     ...       
1                     25       45               107     78     ...       
2                      0        2                 3      0     ...       
2                      0        8                 9      5     ...       
3                      1       39                65      0     ...       
3                      8       12                37      0     ...       
4                      2       25                59     23     ...       
4                     13       33                68      2     ...       
5                      0        9                22      0     ...       
5                      2       14                30      0     ...       
6                      1       27                85      0     ...       
6                      1       37               122      0     ...       
7                     16      123               268      0     ...       
7                     11       92               329      0     ...       
8                     35       22                56      1     ...       
8                     36       19                59      0     ...       
9                      5       54               172      6     ...       
9                      0       43               133      0     ...       

                 referee reversals round sig_attempts sig_strikes  \
fight_id                                                            
0           Leon Roberts         0     1            0           0   
0           Leon Roberts         0     1            0           0   
1             John Sharp         0     3           91          42   
1             John Sharp         0     3          241         141   
2         Steve Perceval         0     1            3           2   
2         Steve Perceval         0     1           20          13   
3         Greg Kleynjans         0     1           66          40   
3         Greg Kleynjans         0     1           45          20   
4             John Sharp         0     3           98          50   
4             John Sharp         0     3           85          48   
5           Leon Roberts         0     1           22  

In [35]:
fight_df_copy.dtypes

name_first           object
name_last            object
win/loss             object
body                 object
body_attempts        object
clinch               object
clinch_attempts      object
distance             object
distance_attempts    object
ground               object
ground_attempts      object
head                 object
head_attempts        object
kd                   object
leg                  object
leg_attempts         object
method               object
pass                 object
referee              object
reversals            object
round                object
sig_attempts         object
sig_strikes          object
strike_attempts      object
strikes              object
sub_attempts         object
takedowns            object
td_attempts          object
dtype: object